### PR TITLE
Set up code-style helpers

### PR DESCRIPTION
**Pull request by rsilivestr**

### CODE REVIEW

**Comment by worldpwn** [comment]
@rsilivestr we should do this under the **lib** folder, so it will not affect the **example** folder.

**Review by worldpwn — CHANGES_REQUESTED** [review]
@rsilivestr we should do this under the lib folder, so it will not affect the example folder.

- [x] move style inside lib folder
- [ ] run formatting against all files inside lib folder

**Comment by rsilivestr** [comment]
>move style inside lib folder

Okay, done. Not sure why example shouldn't be linted tho.

>run formatting against all files inside lib folder

Configured some eslint rules to throw warnings instead of errors, you can fix them yourself or disable those rules completely.

**Review by worldpwn — APPROVED** [review]

**Comment by worldpwn** [comment]
@rsilivestr approved - you can merge it

**Comment by rsilivestr** [comment]
>approved - you can merge it

>Only those with write access to this repository can merge pull requests.

I can not :)

**Comment by worldpwn** [comment]
@rsilivestr  ok :)

**Pull request merged**
