### PR TITLE
Refactor getNodes 

### PR DESCRIPTION
**Pull request by rsilivestr**
- rewrite with built-in array methods
- add test case for an empty nodes array

Btw, why not return an empty array over throwing an error (which is not caught) when there are no nodes in json?

### CODE REVIEW

**Comment by worldpwn** [comment]
@rsilivestr In the libraries, it is better to throw when something goes wrong with a detailed message, so the consumer can fix it. And it is more explicit behavior.

In this case, you are right, if the nodes array is empty we should return an empty one.

**Comment by worldpwn** [comment]
@rsilivestr thank you for adding an empty JSON example and overall good refactoring.

**Review by worldpwn — CHANGES_REQUESTED** [review]
- [ ] return empty array instead of exception

**Comment by rsilivestr** [comment]
>return empty array instead of exception

Done.

**Review by worldpwn — CHANGES_REQUESTED** [review]

**Comment by rsilivestr** [comment]
>return empty array instead of exception
>This error shouldn't be removed, because it dialog has to have starting node

Those two statements seem contradictory. So which one?

>Also, the starting node can be the node that is not the first one.

The `sort` method takes care of that.

Also, can there be unused nodes in input, that should be filtered out? If yes, test for that case is needed.

**Comment by worldpwn** [comment]
@rsilivestr I was talking about:

> In this case, you are right, **if the nodes array is empty** we should return an empty one

but if the starting node is null (get nodes cannot find it) -> it should throw, otherwise how the consumer will understand why do we return empty array of nodes, but there are nodes in the JSON

**Review by worldpwn — APPROVED** [review]

**Pull request merged**
